# Generated by Django 3.0.5 on 2020-11-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfjs_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_file',
            field=models.FileField(blank=True, upload_to='document_files'),
        ),
    ]
