# Generated by Django 3.0.5 on 2020-11-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfjs_book', '0002_document_doc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
